name: Cross-Platform Build & Release

on:
  push:
    tags:
      - "v*"   # Runs only when you push tags like v1.0, v2.0 etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: TrueConnect-linux
            asset_name: TrueConnect-linux.tar.gz
          - os: windows-latest
            artifact_name: TrueConnect-win.exe
            asset_name: TrueConnect-win.exe
          - os: macos-latest
            artifact_name: TrueConnect-mac.dmg
            asset_name: TrueConnect-mac.dmg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas fpdf2

      # Windows Build
      - name: Build Windows Executable
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --hidden-import=fpdf --hidden-import=fpdf.fpdf --hidden-import=pandas main.py
          move dist\main.exe dist\TrueConnect-win.exe
        shell: cmd

      # Linux Build
      - name: Build Linux Executable
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --hidden-import=fpdf --hidden-import=fpdf.fpdf --hidden-import=pandas main.py
          mv dist/main dist/TrueConnect-linux
          tar -czvf dist/TrueConnect-linux.tar.gz -C dist TrueConnect-linux
        shell: bash

      # macOS Build
      - name: Build macOS Executable
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile --hidden-import=fpdf --hidden-import=fpdf.fpdf --hidden-import=pandas main.py
          mv dist/main dist/TrueConnect-mac
          mkdir -p dist/dmg
          cp dist/TrueConnect-mac dist/dmg/
          hdiutil create -volname "TrueConnect" -srcfolder dist/dmg -ov -format UDZO dist/TrueConnect-mac.dmg
        shell: bash

      # Upload artifacts
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.tar.gz
            dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}